---
- include_tasks: dns.yml
  tags: system_dns

- meta: flush_handlers

- include_tasks: upgrade.yml
  tags: system_upgrade

- include_tasks: kernel.yml
  tags: system_kernel

- meta: flush_handlers

- include_tasks: ssh.yml
  tags: system_ssh

- include_tasks: journald.yml
  tags: system_journald
