---
- include_tasks: reality_identity.yml

- name: Generate sing-box config
  ansible.builtin.template:
    src: reality.json.j2
    dest: "{{ singbox_config_path }}"
  notify:
    - Restart sing-box
    - Enable and start sing-box
