---
- name: Check if identity exists
  ansible.builtin.stat:
    path: "{{ singbox_identity_path }}"
  register: singbox_identity_stat

- block:
    - name: Generate sing-box UUID
      ansible.builtin.command: sing-box generate uuid
      register: singbox_uuid
      changed_when: true

    - name: Save identity
      ansible.builtin.copy:
        dest: "{{ singbox_identity_path }}"
        owner: root
        group: root
        mode: "0600"
        content: |
          uuid: "{{ singbox_uuid.stdout | trim }}"

  when: not singbox_identity_stat.stat.exists

- name: Fail if identity file is empty or broken
  ansible.builtin.fail:
    msg: "Identity file exists but is empty or invalid"
  when:
    - singbox_identity_stat.stat.exists
    - singbox_identity_stat.stat.size | default(0) == 0

- name: Load identity
  ansible.builtin.include_vars:
    file: "{{ singbox_identity_path }}"
    name: singbox_identity
