---
- include_tasks: vless_tls_identity.yml

- name: Generate config
  ansible.builtin.template:
    src: vless_tls.json.j2
    dest: "{{ singbox_config_path }}"
  notify:
    - Enable and start sing-box
    - Restart sing-box
