firewall_rules_dir: "/etc/nftables.d"
# firewall_rule_name: "allow_http"
# firewall_rules:
#   - "add rule inet filter input tcp dport 443 accept"
#   - "add rule inet filter input udp dport 443 accept"
