---
- include_tasks: reality_identity.yml

- name: Generate config
  ansible.builtin.template:
    src: reality_sfy.json.j2
    dest: "{{ xray_config_path }}"
  notify:
    - Enable and start Xray
    - Restart xray
