---
- include_tasks: upgrade_pip

- name: Install certbot-dns-cloudflare
  ansible.builtin.pip:
    name: certbot-dns-cloudflare
    virtualenv: "{{ certbot_path }}"
    state: present

- name: Add upgrade cron job
  ansible.builtin.cron:
    name: "certbot-dns-cloudflare auto upgrade"
    minute: "0"
    hour: "0"
    day: "1"
    user: root
    job: "{{ certbot_pip_path }} install --upgrade certbot-dns-cloudflare"
